### ISSUE TITLE
Malformed dataTable header on menu collapse.

### ISSUE THREAD

**Issue by tp0ck3r** [adminfaces/quarkus-admin-showcase#1]
If you collapse the left sidebar the dataTable header behaves a bit strange.
![adminfaces-datatable](https://user-images.githubusercontent.com/1336365/59642374-069a2300-9165-11e9-9425-d1d72e1c34cc.png)

**Comment by rmpestano** [comment]
Hi @tp0ck3r, yes it is related with [stickyHeader](https://github.com/adminfaces/quarkus-admin-showcase/blob/f24030bc6a824ed80c2bb2c422b427ce5ad4bbbd/src/main/resources/META-INF/resources/pages/components/datatable.xhtml#L55), if you turn it to false then it shouldn't happen.

**Comment by rmpestano** [comment]
This issue was just fixed and should be available in adminfaces 1.3.0 to be released today. Thanks for your feedback
